"""Grok media gallery endpoints.

  GET /api/gallery  paginated list of every Grok job that produced media
                    output, with filters by user/profile/job_type/date.
                    Super_admin sees all rows; admin → own domain; user → own.
"""
from __future__ import annotations

import re
import uuid
from datetime import datetime
from typing import Literal

from fastapi import APIRouter, Query
from pydantic import BaseModel
from sqlalchemy import func, select

from app.core.deps import CurrentUser, DbSession
from app.models import Job, Profile, User
from app.modules.grok.files.router import make_share_token

router = APIRouter(prefix="/api/gallery", tags=["gallery"])


# Match `/api/files/<uuid>/download` inside Job.result_url so we can attach
# a short-lived `?token=` for inline rendering by <img>/<video> tags.
_FILE_URL_RE = re.compile(r"^/api/files/([0-9a-f-]{36})/download$")


class GalleryItem(BaseModel):
    job_id: uuid.UUID
    job_type: str
    provider: str
    prompt: str
    result_url: str
    profile_name: str | None
    user_email: str | None
    created_at: datetime
    completed_at: datetime | None
    file_size: int | None


class GalleryPage(BaseModel):
    items: list[GalleryItem]
    total: int
    offset: int
    limit: int


@router.get("", response_model=GalleryPage)
async def list_gallery(
    user: CurrentUser, db: DbSession,
    job_type: Literal["image", "video", ""] = Query(default=""),
    user_id: uuid.UUID | None = Query(default=None),
    profile_id: uuid.UUID | None = Query(default=None),
    date_from: datetime | None = Query(default=None),
    date_to: datetime | None = Query(default=None),
    offset: int = Query(default=0, ge=0),
    limit: int = Query(default=30, ge=1, le=100),
) -> GalleryPage:
    """Scope:
      super_admin → all media in the platform
      admin       → media generated by users in their domain
      user        → their own media only
    """
    base = (
        select(Job, Profile, User)
        .outerjoin(Profile, Profile.id == Job.profile_id)
        .outerjoin(User, User.id == Job.user_id)
        .where(Job.status == "success", Job.result_url.is_not(None))
    )

    if user.role == "user" or user.role == "support":
        base = base.where(Job.user_id == user.id)
    elif user.role == "admin":
        base = base.where(User.domain_id == user.domain_id)

    if job_type:
        base = base.where(Job.job_type == job_type)
    if user_id:
        base = base.where(Job.user_id == user_id)
    if profile_id:
        base = base.where(Job.profile_id == profile_id)
    if date_from:
        base = base.where(Job.created_at >= date_from)
    if date_to:
        base = base.where(Job.created_at <= date_to)

    # Cheap count without ordering / pagination — same WHERE.
    total = (await db.execute(
        select(func.count()).select_from(base.subquery())
    )).scalar_one() or 0

    rows = (await db.execute(
        base.order_by(Job.completed_at.desc().nullslast(), Job.created_at.desc())
        .offset(offset).limit(limit)
    )).all()

    items = []
    for j, p, u in rows:
        raw = j.result_url or ""
        # Sign /api/files/<uuid>/download URLs so the browser can render
        # them in <img>/<video> tags without an Authorization header.
        m = _FILE_URL_RE.match(raw)
        if m:
            try:
                token = make_share_token(uuid.UUID(m.group(1)))
                raw = f"{raw}?token={token}"
            except Exception:  # noqa: BLE001 — never block listing on signing errors
                pass
        items.append(GalleryItem(
            job_id=j.id,
            job_type=j.job_type,
            provider=j.provider,
            prompt=j.prompt or "",
            result_url=raw,
            profile_name=p.name if p else None,
            user_email=u.email if u else None,
            created_at=j.created_at,
            completed_at=j.completed_at,
            file_size=None,
        ))
    return GalleryPage(items=items, total=int(total), offset=offset, limit=limit)
