#!/usr/bin/env python3
"""export_product.py — assemble a standalone product repo from the
monorepo and push it to the customer-facing GitHub remote.

Usage:
    cd <monorepo>
    python products/_scripts/export_product.py <product>
    python products/_scripts/export_product.py <product> --no-push   # dry run
    python products/_scripts/export_product.py <product> --pat GHTOKEN

What it does:
    1. Reads products/<product>/manifest.yaml
    2. Stages a temp dir
    3. Copies backend/ + frontend/ paths from manifest.include
    4. Copies products/<product>/* (Dockerfile, compose, deploy/, ...)
    5. Copies products/_scripts/{customer_setup,customer_update}.sh
    6. Drops files in manifest.drop
    7. Applies manifest.patches (text edits)
    8. Writes app/core/module_registry.py from manifest.module_registry
    9. (Optional) git push --force to manifest.remote.url:branch

The manifest is the source of truth. To add/remove modules from a
product, edit the YAML — don't fork this script.
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("Need PyYAML:  pip install pyyaml")


REPO_ROOT = Path(__file__).resolve().parents[2]      # monorepo root
PRODUCTS_DIR = REPO_ROOT / "products"
SCRIPTS_DIR = PRODUCTS_DIR / "_scripts"


# -------------------------------------------------------------------- helpers

def log(msg: str, *, level: str = "info") -> None:
    color = {"info": "\033[36m", "warn": "\033[33m", "ok": "\033[32m", "err": "\033[31m"}[level]
    print(f"{color}{msg}\033[0m", flush=True)


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    """Run a command, surface stderr on failure."""
    return subprocess.run(cmd, check=True, text=True, **kw)


def copy_path(src: Path, dst: Path) -> None:
    """Copy a file or directory tree, creating parents as needed."""
    if not src.exists():
        log(f"  ! missing: {src.relative_to(REPO_ROOT)}", level="warn")
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.is_dir():
        shutil.copytree(
            src, dst,
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".pytest_cache", "node_modules", "dist"),
        )
    else:
        shutil.copy2(src, dst)


def apply_drops(root: Path, drops: list[str]) -> None:
    """Delete files / dirs listed in `manifest.drop`."""
    for rel in drops:
        target = root / rel
        if target.is_dir():
            shutil.rmtree(target, ignore_errors=True)
        elif target.is_file():
            target.unlink(missing_ok=True)


# -------------------------------------------------------------------- patches

def write_module_registry(stage: Path, modules: list[str]) -> None:
    """Regenerate app/core/module_registry.py with the product's module list.

    The monorepo version loads every module; the product variant must
    only import the ones the product actually ships. Without this rewrite
    the boot fails on `ImportError` for the dropped sibling modules.
    """
    registry = stage / "backend" / "app" / "core" / "module_registry.py"
    if not registry.exists():
        log("  ! module_registry.py not found — skipping rewrite", level="warn")
        return

    imports = "\n".join(
        f"    from {mod} import manifest as {mod.split('.')[-1]}" for mod in modules
    )
    returns = "        " + ",\n        ".join(mod.split(".")[-1] for mod in modules)

    new_load = f'''def _load_modules() -> list[ModuleManifest]:
    """Auto-generated by export_product.py — do not edit by hand."""
{imports}

    return [
{returns},
    ]
'''
    src = registry.read_text(encoding="utf-8")
    pattern = re.compile(
        r"def _load_modules\(\) -> list\[ModuleManifest\]:.*?(?=\n_MODULES|\nMODULES|\ndef [a-z_])",
        re.DOTALL,
    )
    if not pattern.search(src):
        log("  ! could not locate _load_modules() — skipping rewrite", level="warn")
        return
    new_src = pattern.sub(new_load, src, count=1)
    registry.write_text(new_src, encoding="utf-8")
    log(f"  + rewrote module_registry.py with {len(modules)} modules", level="ok")


def apply_text_patches(stage: Path, patches: list[dict]) -> None:
    """Apply the live patches we accumulated during VPS deploy:

    - Strip references to dropped pages from FE router files
    - Strip Profile/Job relationships from User when grok module dropped
    - etc.

    Each patch is a dict with keys `file`, `find`, `replace` (or
    `regex_find`, `regex_replace`).
    """
    for patch in patches or []:
        target = stage / patch["file"]
        if not target.exists():
            log(f"  ! patch target missing: {patch['file']}", level="warn")
            continue
        src = target.read_text(encoding="utf-8")
        if "regex_find" in patch:
            new = re.sub(
                patch["regex_find"], patch.get("regex_replace", ""),
                src, flags=re.DOTALL | re.MULTILINE,
            )
        else:
            new = src.replace(patch["find"], patch.get("replace", ""))
        if new == src:
            log(f"  - patch noop: {patch['file']}", level="warn")
        else:
            target.write_text(new, encoding="utf-8")
            log(f"  + patched {patch['file']}")


# -------------------------------------------------------------------- main

def export_product(name: str, no_push: bool, pat: str | None) -> int:
    manifest_path = PRODUCTS_DIR / name / "manifest.yaml"
    if not manifest_path.exists():
        log(f"manifest not found: {manifest_path}", level="err")
        return 1
    manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8"))

    log(f"== export {name} ({manifest.get('label', '')}) ==")

    with tempfile.TemporaryDirectory(prefix=f"export-{name}-") as tmp:
        stage = Path(tmp) / "stage"
        stage.mkdir()

        # 1. Backend
        log(f"-> copying backend ({len(manifest['include']['backend'])} paths)")
        for rel in manifest["include"]["backend"]:
            copy_path(REPO_ROOT / "backend" / rel, stage / "backend" / rel)
        apply_drops(stage / "backend", manifest.get("drop", {}).get("backend", []))

        # 2. Frontend
        log(f"-> copying frontend ({len(manifest['include']['frontend'])} paths)")
        for rel in manifest["include"]["frontend"]:
            copy_path(REPO_ROOT / "frontend" / rel, stage / "frontend" / rel)
        apply_drops(stage / "frontend", manifest.get("drop", {}).get("frontend", []))

        # 3. Per-product deploy artifacts (compose, Dockerfile, HANDOFF, ...)
        log("-> copying product deploy artifacts")
        for item in (PRODUCTS_DIR / name).iterdir():
            if item.name in {"manifest.yaml", "backend", "frontend", "_bootstrap.py"}:
                continue
            copy_path(item, stage / item.name)

        # 4. Customer scripts (rename without the customer_ prefix at root)
        log("-> copying customer scripts")
        scripts_dst = stage / "_scripts"
        scripts_dst.mkdir(exist_ok=True)
        for script in ("customer_setup.sh", "customer_update.sh", "README.md"):
            copy_path(SCRIPTS_DIR / script, scripts_dst / script)

        # 5. Per-product overrides — anything under products/<name>/overrides/
        #    is copied LAST so it wins over the monorepo version. Use for
        #    files that need a tailored copy (trimmed models/__init__.py,
        #    custom main.py lifespan, etc.).
        overrides_dir = PRODUCTS_DIR / name / "overrides"
        if overrides_dir.is_dir():
            log("-> applying overrides")
            for item in overrides_dir.rglob("*"):
                if item.is_dir():
                    continue
                rel = item.relative_to(overrides_dir)
                copy_path(item, stage / rel)
                log(f"  + override {rel}")

        # 6. Module registry rewrite
        write_module_registry(stage, manifest.get("module_registry", {}).get("backend", []))

        # 7. Text patches
        apply_text_patches(stage, manifest.get("patches", []))

        log("  staged at " + str(stage), level="ok")

        if no_push:
            # Use a timestamped dir so back-to-back runs don't trip on
            # python keeping the previous *.pyc open inside dist/.
            from datetime import datetime
            ts = datetime.now().strftime("%Y%m%d-%H%M%S")
            out = REPO_ROOT / "dist" / f"{name}-{ts}"
            shutil.copytree(stage, out)
            log(f"DRY RUN: wrote staged tree to {out.relative_to(REPO_ROOT)}", level="ok")
            return 0

        # 7. Git push
        remote = manifest["remote"]["url"]
        branch = manifest["remote"].get("branch", "main")
        if pat:
            # inject pat into URL: https://USER:TOKEN@github.com/...
            remote = re.sub(r"^https://", f"https://x-access-token:{pat}@", remote)

        log(f"-> git push --force {remote} HEAD:{branch}")
        run(["git", "init", "-q", "-b", branch], cwd=stage)
        run(["git", "add", "-A"], cwd=stage)
        run([
            "git", "-c", "user.email=export@plxeditor.com",
            "-c", "user.name=GrokFlow Export",
            "commit", "-q", "-m", f"chore({name}): export from monorepo {get_short_sha()}",
        ], cwd=stage)
        run(["git", "push", "--force", remote, f"HEAD:{branch}"], cwd=stage)
        log("OK pushed", level="ok")
        return 0


def get_short_sha() -> str:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=REPO_ROOT, text=True,
        ).strip()
        return out
    except Exception:
        return "unknown"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("product", help="folder under products/, e.g. flowgrok")
    ap.add_argument("--no-push", action="store_true", help="stage only, don't git push")
    ap.add_argument(
        "--pat",
        default=os.getenv("GITHUB_PAT") or os.getenv("GH_TOKEN"),
        help="GitHub PAT (or set $GITHUB_PAT)",
    )
    args = ap.parse_args()
    return export_product(args.product, args.no_push, args.pat)


if __name__ == "__main__":
    sys.exit(main())
