"""Auto-sync nginx vhost configs from Domain rows.

Backend writes `.conf` files into a directory the host nginx includes. A
host-side reloader (cron / systemd path unit) picks up changes and runs
`nginx -s reload`. This avoids needing root/SSH from the container.

Config dir is configurable via `NGINX_VHOSTS_DIR` env. Defaults to
`/host_nginx_vhosts` which the docker-compose mounts from the host's
`/etc/nginx/grokflow-vhosts/` (created by deploy/setup-host-nginx.sh).

Files are named `grokflow-<sanitized-hostname>.conf` so they don't collide
with admin's other configs. Wildcard '*' is the default fallback row in DB
and intentionally has no vhost file (the host's existing default_server
or non-matching catch-all handles it).
"""
from __future__ import annotations

import os
import re
from pathlib import Path

# Where to write vhost files. Host mounts /etc/nginx/grokflow-vhosts/ here.
VHOSTS_DIR = Path(os.environ.get("NGINX_VHOSTS_DIR", "/host_nginx_vhosts"))

# Where to send proxy_pass — must be the host port that maps to the
# grokflow-frontend container (currently 127.0.0.1:5173 on host).
FRONTEND_UPSTREAM = os.environ.get("NGINX_FRONTEND_UPSTREAM", "http://127.0.0.1:5173")
# Backend (FastAPI) upstream — must serve /api/* and /openapi.json.
BACKEND_UPSTREAM = os.environ.get("NGINX_BACKEND_UPSTREAM", "http://127.0.0.1:8000")

# Safe-hostname regex. Anything outside this set is rejected (the admin UI
# should already validate, but defense in depth).
_HOSTNAME_RE = re.compile(r"^[a-z0-9]([a-z0-9\-\.]{0,253}[a-z0-9])?$")


def _is_writable() -> bool:
    """True when the mounted dir exists and is writable.

    Returns False on dev machines / tests where the dir isn't mounted —
    callers should treat this as "skip silently" to keep tests passing
    without host nginx infrastructure.
    """
    try:
        return VHOSTS_DIR.exists() and os.access(VHOSTS_DIR, os.W_OK)
    except OSError:
        return False


def _safe_hostname(hostname: str) -> str | None:
    """Sanitize + validate. Returns None if hostname is unsafe."""
    h = hostname.strip().lower()
    if h == "*" or not h:
        return None
    if not _HOSTNAME_RE.match(h):
        return None
    return h


def _config_path(hostname: str) -> Path:
    safe = hostname.replace(".", "_")
    return VHOSTS_DIR / f"grokflow-{safe}.conf"


def _render_vhost(hostname: str) -> str:
    return f"""# Auto-generated by GrokFlow admin — do not edit by hand.
# Domain row: {hostname}
server {{
    listen 80;
    server_name {hostname};

    client_max_body_size 25m;

    # API + docs go to FastAPI. Listed first so they win the longest-prefix
    # match over the catch-all `/` location below.
    location ~ ^/(api|openapi.json|docs|redoc)(/|$) {{
        proxy_pass {BACKEND_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        proxy_buffering off;
    }}

    # /vnc/<short>/... → kasmweb container on docker bridge.
    # $vnc_upstream is set by the map in _vnc_map.conf (same dir as this file).
    # Backend refreshes that map whenever a VNC container spawns / dies.
    location ~ ^/vnc/([a-f0-9]+)/(.*)$ {{
        set $vnc_short $1;
        set $vnc_rest  $2;
        if ($vnc_upstream = "_none_") {{
            return 502 "VNC container not registered yet — retry Auto login.";
        }}
        proxy_pass http://$vnc_upstream:6901/$vnc_rest$is_args$args;
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # WebSocket upgrade for websockify
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_read_timeout  86400s;
        proxy_send_timeout  86400s;
        proxy_buffering off;
    }}

    location / {{
        proxy_pass {FRONTEND_UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        proxy_buffering off;
    }}
}}
"""


# ─── VNC map (short_id → container IP) ─────────────────────────────────────
#
# Each kasmweb VNC container we spawn is named `grokflow-vnc-<short_id>` where
# <short_id> is the first 12 hex of the profile's UUID. The vhost /vnc/<short>/
# location proxies to the container's bridge IP via the nginx `map` defined
# in `_vnc_map.conf`. We write the map at HTTP context (top-level conf in the
# vhosts dir — included via /etc/nginx/conf.d/grokflow-vhosts.conf).
#
# Called by:
#   - profiles router on start-vnc-session / finish-vnc-session / stop-vnc
#   - app startup (best-effort sync after a fresh container)
VNC_MAP_PATH = VHOSTS_DIR / "_vnc_map.conf"


def refresh_vnc_map() -> bool:
    """Rebuild _vnc_map.conf from currently running VNC containers.

    Idempotent. Returns True on write, False on skip (no docker SDK, dir not
    writable, or no docker.sock). Never raises — callers should treat the
    map as best-effort; existing entries keep working until next refresh.
    """
    if not _is_writable():
        return False
    try:
        import docker  # imported lazily so unit tests don't need it
        client = docker.from_env()
    except Exception:
        return False

    lines: list[str] = [
        "# Auto-generated by GrokFlow backend — do not edit by hand.",
        "# Maps VNC short_id (first 12 hex of profile UUID) -> container IP.",
        "# Refreshed whenever a VNC container is spawned or torn down.",
        "map $vnc_short $vnc_upstream {",
    ]
    try:
        for c in client.containers.list(filters={"name": "grokflow-vnc-"}):
            if not c.name.startswith("grokflow-vnc-"):
                continue
            short = c.name[len("grokflow-vnc-"):]
            # Iterate networks; pick the first non-empty IPv4.
            ip = None
            for net in (c.attrs.get("NetworkSettings", {}).get("Networks") or {}).values():
                addr = net.get("IPAddress")
                if addr:
                    ip = addr
                    break
            if short and ip:
                lines.append(f"    {short} {ip};")
    except Exception:
        # Even if docker is reachable, container listing can race — return what
        # we have (default fallback keeps existing entries working until next
        # successful refresh).
        pass

    lines.append('    default "_none_";')
    lines.append("}")
    text = "\n".join(lines) + "\n"

    try:
        VNC_MAP_PATH.write_text(text, encoding="utf-8")
        return True
    except OSError:
        return False


def write_vhost(hostname: str) -> bool:
    """Idempotently write the nginx vhost file for a domain.

    Returns True on success, False on skip (unsafe hostname, dir not mounted,
    or write error). Callers should NOT raise — domain CRUD must succeed even
    if nginx sync is broken.
    """
    if not _is_writable():
        return False
    h = _safe_hostname(hostname)
    if not h:
        return False
    path = _config_path(h)
    try:
        path.write_text(_render_vhost(h), encoding="utf-8")
        return True
    except OSError:
        return False


def delete_vhost(hostname: str) -> bool:
    """Remove the nginx vhost file for a domain. Idempotent."""
    if not _is_writable():
        return False
    h = _safe_hostname(hostname)
    if not h:
        return False
    path = _config_path(h)
    try:
        path.unlink(missing_ok=True)
        return True
    except OSError:
        return False
